export const ROOMMATE_LIST_REQUEST = "ROOMMATE_LIST_REQUEST";
export const ROOMMATE_LIST_SUCCESS = "ROOMMATE_LIST_SUCCESS";
export const ROOMMATE_LIST_FAIL = "ROOMMATE_LIST_FAIL";

export const ROOMMATE_DETAILS_SUCCESS = "ROOMMATE_DETAILS_SUCCESS";
export const ROOMMATE_DETAILS_REQUEST = "ROOMMATE_DETAILS_REQUEST";
export const ROOMMATE_DETAILS_FAIL = "ROOMMATE_DETAILS_FAIL";

export const ROOMMATE_DELETE_SUCCESS = "ROOMMATE_DELETE_SUCCESS";
export const ROOMMATE_DELETE_REQUEST = "ROOMMATE_DELETE_REQUEST";
export const ROOMMATE_DELETE_FAIL = "ROOMMATE_DELETE_FAIL";

export const ROOMMATE_CREATE_SUCCESS = "ROOMMATE_CREATE_SUCCESS";
export const ROOMMATE_CREATE_REQUEST = "ROOMMATE_CREATE_REQUEST";
export const ROOMMATE_CREATE_FAIL = "ROOMMATE_CREATE_FAIL";
export const ROOMMATE_CREATE_RESET = "ROOMMATE_CREATE_RESET";

export const ROOMMATE_UPDATE_SUCCESS = "ROOMMATE_UPDATE_SUCCESS";
export const ROOMMATE_UPDATE_REQUEST = "ROOMMATE_UPDATE_REQUEST";
export const ROOMMATE_UPDATE_FAIL = "ROOMMATE_UPDATE_FAIL";
export const ROOMMATE_UPDATE_RESET = "ROOMMATE_UPDATE_RESET";

export const ROOMMATE_CREATE_REVIEW_SUCCESS = "ROOMMATE_CREATE_COMMENT_SUCCESS";
export const ROOMMATE_CREATE_COMMENT_REQUEST =
  "ROOMMATE_CREATE_COMMENT_REQUEST";
export const ROOMMATE_CREATE_COMMENT_FAIL = "ROOMMATE_CREATE_COMMENT_FAIL";
export const ROOMMATE_CREATE_COMMENT_RESET = "ROOMMATE_CREATE_COMMENT_RESET";

export const ROOMMATE_TOP_SUCCESS = "ROOMMATE_TOP_SUCCESS";
export const ROOMMATE_TOP_REQUEST = "ROOMMATE_TOP_REQUEST";
export const ROOMMATE_TOP_FAIL = "ROOMMATE_TOP_FAIL";
