export const FURNITURE_LIST_REQUEST = "FURNITURE_LIST_REQUEST";
export const FURNITURE_LIST_SUCCESS = "FURNITURE_LIST_SUCCESS";
export const FURNITURE_LIST_FAIL = "FURNITURE_LIST_FAIL";

export const FURNITURE_DETAILS_SUCCESS = "FURNITURE_DETAILS_SUCCESS";
export const FURNITURE_DETAILS_REQUEST = "FURNITURE_DETAILS_REQUEST";
export const FURNITURE_DETAILS_FAIL = "FURNITURE_DETAILS_FAIL";

export const FURNITURE_DELETE_SUCCESS = "FURNITURE_DELETE_SUCCESS";
export const FURNITURE_DELETE_REQUEST = "FURNITURE_DELETE_REQUEST";
export const FURNITURE_DELETE_FAIL = "FURNITURE_DELETE_FAIL";

export const FURNITURE_CREATE_SUCCESS = "FURNITURE_CREATE_SUCCESS";
export const FURNITURE_CREATE_REQUEST = "FURNITURE_CREATE_REQUEST";
export const FURNITURE_CREATE_FAIL = "FURNITURE_CREATE_FAIL";
export const FURNITURE_CREATE_RESET = "FURNITURE_CREATE_RESET";

export const FURNITURE_UPDATE_SUCCESS = "FURNITURE_UPDATE_SUCCESS";
export const FURNITURE_UPDATE_REQUEST = "FURNITURE_UPDATE_REQUEST";
export const FURNITURE_UPDATE_FAIL = "FURNITURE_UPDATE_FAIL";
export const FURNITURE_UPDATE_RESET = "FURNITURE_UPDATE_RESET";

export const FURNITURE_CREATE_COMMENT_SUCCESS =
  "FURNITURE_CREATE_COMMENT_SUCCESS";
export const FURNITURE_CREATE_COMMENT_REQUEST =
  "FURNITURE_CREATE_COMMENT_REQUEST";
export const FURNITURE_CREATE_COMMENT_FAIL = "FURNITURE_CREATE_COMMENT_FAIL";
export const FURNITURE_CREATE_COMMENT_RESET = "FURNITURE_CREATE_COMMENT_RESET";

export const FURNITURE_TOP_SUCCESS = "FURNITURE_TOP_SUCCESS";
export const FURNITURE_TOP_REQUEST = "FURNITURE_TOP_REQUEST";
export const FURNITURE_TOP_FAIL = "FURNITURE_TOP_FAIL";
