export const HOUSE_LIST_REQUEST = "HOUSE_LIST_REQUEST";
export const HOUSE_LIST_SUCCESS = "HOUSE_LIST_SUCCESS";
export const HOUSE_LIST_FAIL = "HOUSE_LIST_FAIL";

export const HOUSE_DETAILS_SUCCESS = "HOUSE_DETAILS_SUCCESS";
export const HOUSE_DETAILS_REQUEST = "HOUSE_DETAILS_REQUEST";
export const HOUSE_DETAILS_FAIL = "HOUSE_DETAILS_FAIL";

export const HOUSE_DELETE_SUCCESS = "HOUSE_DELETE_SUCCESS";
export const HOUSE_DELETE_REQUEST = "HOUSE_DELETE_REQUEST";
export const HOUSE_DELETE_FAIL = "HOUSE_DELETE_FAIL";

export const HOUSE_CREATE_SUCCESS = "HOUSE_CREATE_SUCCESS";
export const HOUSE_CREATE_REQUEST = "HOUSE_CREATE_REQUEST";
export const HOUSE_CREATE_FAIL = "HOUSE_CREATE_FAIL";
export const HOUSE_CREATE_RESET = "HOUSE_CREATE_RESET";

export const HOUSE_UPDATE_SUCCESS = "HOUSE_UPDATE_SUCCESS";
export const HOUSE_UPDATE_REQUEST = "HOUSE_UPDATE_REQUEST";
export const HOUSE_UPDATE_FAIL = "HOUSE_UPDATE_FAIL";
export const HOUSE_UPDATE_RESET = "HOUSE_UPDATE_RESET";

export const HOUSE_CREATE_COMMENT_SUCCESS = "HOUSE_CREATE_COMMENT_SUCCESS";
export const HOUSE_CREATE_COMMENT_REQUEST = "HOUSE_CREATE_COMMENT_REQUEST";
export const HOUSE_CREATE_COMMENT_FAIL = "HOUSE_CREATE_COMMENT_FAIL";
export const HOUSE_CREATE_COMMENT_RESET = "HOUSE_CREATE_COMMENT_RESET";

export const HOUSE_TOP_SUCCESS = "HOUSE_TOP_SUCCESS";
export const HOUSE_TOP_REQUEST = "HOUSE_TOP_REQUEST";
export const HOUSE_TOP_FAIL = "HOUSE_TOP_FAIL";
